envie-tmp: requirements files are given always relative to script's path

diff --git a/scripts/envie-tmp b/scripts/envie-tmp
--- a/scripts/envie-tmp
+++ b/scripts/envie-tmp
@@ -15,15 +15,16 @@
 # If requirements specified as "auto", the closest "requirements.txt" is searched for.
 # Alternatively, you can specify a different, or a specific pip requirements, like:
 #
-#   # -*- requirements: test-requirements.txt dev-requirements.txt -*-
+#   # -*- requirements: ../base-requirements.txt ./dev-requirements.txt -*-
 #
+# Paths to requirements files are relative to the SCRIPT's dir.
 #
-# Part of the ``envie`` package, ``https://github.com/randomir/envie``.
+# ``envie-tmp`` is part of the ``envie`` package, ``https://github.com/randomir/envie``.
 
 
 usage() {
     echo "Create a new temporary (throw-away) virtual environment, install requirements"
-    echo "specified, run the SCRIPT, and destroy the environment when the script finishes."
+    echo "specified, run the SCRIPT, and destroy the environment afterwards."
     echo
     echo "Usage:"
     echo "    envie-tmp SCRIPT"
@@ -39,35 +40,37 @@ usage() {
     echo "    #!/usr/bin/env envie-tmp"
     echo "    # -*- requirements: auto -*-"
     echo
-    echo " 3) installs reqs from the closest custom-named Pip requirements files:"
-    echo "    (mkenv -ta -r REQ ...)"
+    echo " 3) installs reqs from the specific Pip requirements files (relative to SCRIPT's dir)"
+    echo "    (mkenv -ta -r REQ ...):"
     echo
     echo "    #!/usr/bin/env envie-tmp"
-    echo "    # -*- requirements: test-requirements.txt dev-requirements.txt -*-"
+    echo "    # -*- requirements: ../base-requirements.txt ./dev-requirements.txt -*-"
     echo
 }
 
 
 mkenv_based_on_script_reqs() {
-    local script="$1"
-    local reqs=$(sed -nre "s/^[ \t\v]*#.*?requirements[:=][ \t]*(.+) -\*-[ \t\v]*$/\1/p" "$script" | paste -sd' ')
-    local req subreq opts=(-t -q)
+    # assert: started in script_dir (reqs are relative to script!)
+    local path="$1"
+    local reqs=$(sed -nre "s/^[ \t\v]*#.*?requirements[:=][ \t]*(.+) -\*-[ \t\v]*$/\1/p" "$path" | paste -sd' ')
+    local req opts=(-t -q)
     for req in $reqs; do
         if [ "$req" == "auto" ]; then
             opts+=(-a)
         else
-            for subreq in "$(_find_closest "$req" ".")"; do
-                opts+=(-r "$subreq")
-            done
+            if [ ! -f "$req" ]; then
+                echo "ERROR: requirement file not found: $req"
+                exit 3
+            fi
+            opts+=(-r "$req")
         fi
     done
-
     mkenv "${opts[@]}"
 }
 
 
 if ! command -v envie &>/dev/null; then
-    echo "Envie not found. Install with: 'sudo pip install envie'."
+    echo "ERROR: Envie not found. Install with: 'sudo pip install envie'."
     exit 1
 fi
 
@@ -75,21 +78,21 @@ if [ ! "$1" ] || [ "$1" == "--help" ] || [ "$1" == "-h" ]; then
     usage
     exit 255
 fi
-user_script="$1"
+script_path="$1"
 
 # source envie (we need _find_closest later on), don't pass-through our args
 set --
 . envie
 
-if [ ! -r "$user_script" ]; then
-    echo "Script not found or not readable: '$user_script'."
+if [ ! -r "$script_path" ]; then
+    echo "ERROR: script not found or not readable: '$script_path'."
     exit 2
 fi
-script_dir=$(_readlink "$(dirname "$user_script")")
+script_dir=$(_readlink "$(dirname "$script_path")")
 
 (
     cd "$script_dir"
-    mkenv_based_on_script_reqs "$user_script" && created=1
-    (( created )) && python "$user_script"
+    mkenv_based_on_script_reqs "$script_path" && created=1
+    (( created )) && python "$script_path"
     (( created )) && rmenv -f
 )
